### ISSUE TITLE
Unable to UpdateRecord

### ISSUE THREAD

**Issue by ponasromas** [cloudflare/cloudflare-php#111]
I'am unable to update record. Specifically to disable Cloudflare proxy. Code:

```
$key = new \Cloudflare\API\Auth\APIKey('user@email.tld', '123...');
$adapter = new Cloudflare\API\Adapter\Guzzle($key);
$zones = new \Cloudflare\API\Endpoints\Zones($adapter);
$zoneID = $zones->getZoneID("domain.tld");

$details = [
    'proxied' => false,
];

$recordID = '123...';

$dns = new \Cloudflare\API\Endpoints\DNS($adapter);
$output= $dns->updateRecordDetails($zoneID, '$recordID', $details);
```

Output:

>  response: {"success":false,"errors":[{"code":1004,"message":"DNS Validation Error","error_chain":

**Comment by beltofte** [comment]
Is it working if you do a patch request to the API using Postman or similar tool?

**Comment by pauladams8** [comment]
Looking at the error message, it suggests the record you are trying to update is malformed. The full response may provide more details.

**Comment by haphan** [comment]
@ponasromas  `$details` needs to contains all required fields `type`, `name`, `content` and `ttl`. 

See [api doc](https://api.cloudflare.com/#dns-records-for-a-zone-update-dns-record)

**Comment by ponasromas** [comment]
Issue still not resolved, all details provided. Error:

```
resulted in a `400 Bad Request` response:
{"result":null,"success":false,"errors":[{"code":9207,"message":"Failed to parse request body...<...>
```

Request:

`$dns->updateRecordDetails($zoneID, $rid, array($type, $name, $content, $ttl, true));`

Does this API SDK still maintained?

**Comment by ponasromas** [comment]
Fixed.
