### ISSUE TITLE
Deprecated: Array and string offset access syntax with curly braces

### ISSUE THREAD

**Issue by tobsn** [cloudflare/cloudflare-php#116]
`Deprecated: Array and string offset access syntax with curly braces is deprecated in ...cloudflare/sdk/src/Endpoints/DNS.php on line 131`

Probably needs some love on 7.4

**Comment by aaronhuisinga** [comment]
There is an open PR to fix this #114

**Comment by IcyApril** [comment]
Thanks folks! Should be fixed in the new release.
