### ISSUE TITLE
Is this library still maintained?

### ISSUE THREAD

**Issue by pauladams8** [cloudflare/cloudflare-php#117]
I would like to use this library for a project, but there are so many problems with it currently that it is easier to just communicate with the Cloudflare API manually.

At the moment, this library lacks many features of the Cloudflare API and does not seem to be actively maintained.

Some issues that need addressing:
- PHP syntax issues (see PR #114)
- API token support (see PR #101)
- Inconsistent return types
- Inconsistent code style

It would also be good to see some work on integrating other API endpoints, I submitted a PR a while back and there are some others that could be merged.

**Comment by marktastic** [comment]
I would also like to add: The Zone Analytics API being deprecated (May 31, 2020) in favor of the GraphQL Analytics API should be handled here somehow as well.

**Comment by levidurfee** [comment]
I started a project: https://github.com/wappr/cloudflare-graphql

**Comment by IcyApril** [comment]
Sorry for the delay here - I was away in December and been quite busy recently. I've merged a lot of the awaiting PRs updated the release. Thanks everyone.
