### ISSUE TITLE
Missing Tag

### ISSUE THREAD

**Issue by Rohop13** [cloudflare/cloudflare-php#120]
It looks like the latest update has not been tagged

So this: https://github.com/cloudflare/cloudflare-php/blob/master/src/Endpoints/Zones.php

is out of date on this: https://packagist.org/packages/cloudflare/sdk#1.1.4

Meaning that features are missing

**Comment by IcyApril** [comment]
Hi @Rohop13 - sorry for the delay, I've published a new release for 1.1.5.
