### ISSUE TITLE
Adding MX records with priority 0 fails

### ISSUE THREAD

**Issue by pjjonesnz** [cloudflare/cloudflare-php#136]
I came across this while setting up MX records for Microsoft 365. Their suggested setting for the priority of their MX record is 0.

When I tried to update my DNS record using a priority 0, I received the following error: 

```json
{"result":null,"success":false,"errors":[{"code":1004,"message":"DNS Validation Error","error_chain":[{"code":9100,"message":"priority is a required field."}]}],"messages":[]}
```

Any other priority works, and I've traced it back to a issue with the addRecord function.

I've created a fix for it. Hopefully this is helpful.

#135

**Comment by haphan** [comment]
@IcyApril  please help to close this issue too :)

**Comment by pjjonesnz** [comment]
I see that this was merged in a few days ago. Thanks so much!
