### ISSUE TITLE
Purge cache is not working

### ISSUE THREAD

**Issue by NathanStrobbe** [cloudflare/cloudflare-php#137]
Hi, the method to purge the cache is not working since a few weeks. I'm currently using the method
`Zones::cachePurge()` but it doesn't seem to work properly.
But checking the Cloudflare API v4 and the code, I notice that the Cloudflare API requires a POST method but this library is using DELETE. So I'm proposing a fix.

**Comment by haphan** [comment]
Please help to close this issue @IcyApril

**Comment by NathanStrobbe** [comment]
My bad, I thought that the issue has been closed automatically when the merge was done.
