### ISSUE TITLE
Update dependencies to Guzzle 7

### ISSUE THREAD

**Issue by MickaelTH** [cloudflare/cloudflare-php#159]
Hi,

Is it possible to have an update of this package to use Guzzle 7?

https://github.com/guzzle/guzzle/releases

Thanks

**Comment by zharding** [comment]
I agree. 

The current lock @ version 6 is preventing many from moving forward on updating their applications.

**Comment by MickaelTH** [comment]
@zharding Didn't found that when searching for issue, not sure how I missed it, thanks a lot!
