### ISSUE TITLE
Move friendsofphp/php-cs-fixer to dev requirement

### ISSUE THREAD

**Issue by dol** [cloudflare/cloudflare-php#16]
I guess the friendsofphp/php-cs-fixer dependency is only used for local development. Consider moving the dependency to 'require-dev'.
The packages has quite a few dependencies that pulled in. See https://packagist.org/packages/friendsofphp/php-cs-fixer

**Comment by IcyApril** [comment]
Thanks for flagging this. Fixing in https://github.com/cloudflare/cloudflare-php/pull/17
