### ISSUE TITLE
Errors while install it on Laravel 8 and PHP 8

### ISSUE THREAD

**Issue by andreapollastri** [cloudflare/cloudflare-php#175]
Hi, no way to solve several errors trying to install Cloudflare SDK into Laravel 8 within PHP8. Please... update your packages! Thank You

**Comment by Cannonb4ll** [comment]
Experiencing the same, would be great to have PHP 8 support ready to go. (As well as Laravel 8)

**Comment by stayallive** [comment]
1.1.7 was released 3 days ago which should work with Guzzle 7 and thus Laravel 8. If you have trouble with 1.1.7 show the error you are getting because it might not be the same.

**Comment by Cannonb4ll** [comment]
I see now indeed, thanks! Missed it for some reason.

**Comment by andreapollastri** [comment]
Solved, Thank You!
