### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by shadowlmd** [cloudflare/cloudflare-php#33]
Hello,

Would be nice to have some documentation with examples of some complex methods, like page rules, DNS records, etc.

**Comment by IcyApril** [comment]
HI @shadowlmd;

There are some examples on our Knowledge Base: https://support.cloudflare.com/hc/en-us/articles/115001661191-Cloudflare-PHP-API-Binding

Do these work for you, or would you like us to add something else?

**Comment by shadowlmd** [comment]
Yep, these should do. I wonder how I could miss this link. Sorry, my bad.
