### ISSUE TITLE
CustomHostnames lack ability to set the "custom_origin_server" parameter

### ISSUE THREAD

**Issue by DaazKu** [cloudflare/cloudflare-php#56]
Both the [documentation](https://api.cloudflare.com/#custom-hostname-for-a-zone-create-custom-hostname) and the [API](https://github.com/cloudflare/cloudflare-php/blob/63be6cf1549eed4cb0f6c1bd12eb4d940dc339bf/src/Endpoints/CustomHostnames.php#L32) are missing the "custom_origin_server" parameter.

```http
POST /client/v4/zones/REDACTED/custom_hostnames
Accept: */*
Accept-Encoding: gzip, deflate
X-Auth-Email: REDACTED
X-Auth-Key: REDACTED
Content-Type: application/json
Accept-Language: en-ca
{
  "custom_origin_server": "REDACTED",
  "hostname": "REDACTED",
  "ssl": {
    "method": "http",
    "type": "dv"
  }
}
```

```json
{
    "result": {
        "id": "REDACTED",
        "hostname": "REDACTED",
        "ssl": {
            "id": "REDACTED",
            "type": "dv",
            "method": "http",
            "status": "initializing"
        },
        "custom_origin_server": "REDACTED"
    },
    "success": true
}
```

![screen shot 2018-06-26 at 3 26 29 pm](https://user-images.githubusercontent.com/2412909/41934689-565a4ee8-7955-11e8-9c09-85151198ad12.png)

**Comment by phily245** [comment]
I can see support for this has been added to the SDK but the docs are missing it, is this publicly editable?
