### ISSUE TITLE
Cache purge requests should not contain null as a value

### ISSUE THREAD

**Issue by garrettgalow** [cloudflare/cloudflare-php#59]
see https://github.com/cloudflare/cloudflare-php/blob/63be6cf1549eed4cb0f6c1bd12eb4d940dc339bf/src/Endpoints/Zones.php#L161

this ends up passing 'tag' => null if no tags (or files I assume) are passed. This is in violation of the API contract which is now being enforced

**Comment by IcyApril** [comment]
Closing into #61
