### ISSUE TITLE
Cache purge Error 1014 

### ISSUE THREAD

**Issue by romanoffs** [cloudflare/cloudflare-php#61]
My request : 
        $zones->cachePurge($zoneID, [$url], []);

But the response contains this error, what's the problem?

{"success":false,"errors":[{"code":1014,"message":"\"files\", \"tags\", or \"hosts\" must be an array"}],"messages":[]," (truncated...)

**Comment by garrettgalow** [comment]
this looks to be a dupe of #59 or at least related

**Comment by ljoseppi** [comment]
I've replaced lines 167-170 of file Endpoints/Zones.php with:
`$options = [];
 $files AND $options['files'] = $files;
 $tags AND $options['tags'] = $tags;`

**Comment by emgk** [comment]
Hey @IcyApril I'm using call `https://api.cloudflare.com/client/v4/` endpoint and still getting the same error.
