### ISSUE TITLE
Creating a SRV record does not work

### ISSUE THREAD

**Issue by kruisdraad** [cloudflare/cloudflare-php#67]
Ill be submitting a PR linking to this issue, but the SDK is missing code to create and update SRV records and the fix seems simple enough.

In addition, if you change items like proto with a bad value 'tcp' instead of '_tcp' it the API cannot handle the error message and shows %s:

Caught exception: Client error: `POST https://api.cloudflare.com/client/v4/zones/xxxxxxx/dns_records` resulted in a `400 Bad Request` response:
{"success":false,"errors":[{"code":1004,"message":"DNS Validation Error","error_chain":**[{"code":9150,"message":"%s"}]}]**,"messages":[],"result":null}

**Comment by kruisdraad** [comment]
example for documentation:

  $srvdata = [
    'weight'    => 100,
    'priority'  => 100,
    'proto'     => '_tcp',
    'port'      => 1111,
    'target'    => 'a.x.c.',
    'service'   => '_test.v1'
  ];

  if ($dns->addRecord($zoneID, "SRV", '', '', 120, false, '', $srvdata) === true) {
    echo "DNS record created.". PHP_EOL;
  }

**Comment by brentybh** [comment]
Same issue...

**Comment by brentybh** [comment]
OK, added a new domain to test this issue, then I got some important thing to fix this.
Here's an correct example to POST dns_records to add SRV record. I test that manually and succeed.
Implement that to PHP code then should be fine.
```
{
  "zone_name": "example.com",
  "zone_id": "29d3ceb132d97a6f173d57b74f30bad1",
  "type": "SRV",
  "name": "_servicename._tcp.example.com.",
  "content": "SRV 0 0 443 exampleservice.com.",
  "meta": {},
  "data": {
    "priority": 0,
    "weight": 0,
    "port": 443,
    "target": "exampleservice.com",
    "service": "_servicename",
    "proto": "_tcp",
    "name": "example.com"
  },
  "proxied": false,
  "proxiable": false,
  "ttl": 1,
  "priority": 1
}
```

**Comment by brentybh** [comment]
You're right. `proto` should be `_tcp` but not `tcp`. For those who met this issue.
